name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Set up Java 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Capacitor and Android Engine
      run: |
        npm init -y
        npm install @capacitor/core @capacitor/cli @capacitor/android
        npx cap init APKAnalyzer com.vektorzero.app --web-dir .
        npx cap add android
        npx cap sync

    - name: Build Debug APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: APK-Static-Analyzer-Debug
        path: android/app/build/outputs/apk/debug/app-debug.apkuild/app/outputs/flutter-apk/app-debug.apk
